-- renamed variables, joined other tables, removed redundant columns --
SELECT p.[ProductKey] AS [Product Key]
      ,p.[ProductAlternateKey] AS [Product Code]
      ,p.[ProductSubcategoryKey] AS [Category Key]
      ,pc.EnglishProductCategoryName AS [Product Category]
      ,ps.EnglishProductSubcategoryName AS [Product Subcategory]
    --   ,[WeightUnitMeasureCode]
    --   ,[SizeUnitMeasureCode]
      ,p.[EnglishProductName] AS [Product Name]
    --   ,[SpanishProductName]
    --   ,[FrenchProductName]
      ,p.[StandardCost] AS [Product Cost]
    --   ,[FinishedGoodsFlag]
      ,p.[Color] AS [Product Colour]
    --   ,[SafetyStockLevel]
    --   ,[ReorderPoint]
    --   ,[ListPrice]
      ,p.[Size] AS [Product Size]
    --   ,[SizeRange]
    --   ,[Weight]
    --   ,[DaysToManufacture]
      ,p.[ProductLine] AS [Product Line]
    --   ,[DealerPrice]
      ,p.[Class] AS [Product Class]
    --   ,[Style]
      ,p.[ModelName] AS [Product Model]
    --   ,[LargePhoto]
      ,p.[EnglishDescription] AS [Product Description]
    --   ,[FrenchDescription]
    --   ,[ChineseDescription]
    --   ,[ArabicDescription]
    --   ,[HebrewDescription]
    --   ,[ThaiDescription]
    --   ,[GermanDescription]
    --   ,[JapaneseDescription]
    --   ,[TurkishDescription]
      ,p.[StartDate] AS [Product Date]
    --   ,[EndDate]
      ,p.[Status] AS [Product Status]
  FROM [AdventureWorksDW2025].[dbo].[DimProduct] AS p
  -- joined product subcategory table on ProdSubcategory key --
  LEFT JOIN dbo.DimProductSubcategory as ps ON ps.ProductSubcategoryKey = p.ProductSubcategoryKey
  -- joined product category table on ProdCategory key --
  LEFT JOIN dbo.DimProductCategory AS pc ON pc.ProductCategoryKey = ps.ProductCategoryKey
  ORDER BY p.ProductKey ASC