-- removed redundant columns
SELECT [ProductKey]
      ,[OrderDateKey]
      ,[DueDateKey]
      ,[ShipDateKey]
      ,[CustomerKey]
    --   ,[PromotionKey]
    --   ,[CurrencyKey]
    --   ,[SalesTerritoryKey]
      ,[SalesOrderNumber]
    --   ,[SalesOrderLineNumber]
    --   ,[RevisionNumber]
    --   ,[OrderQuantity]
    --   ,[UnitPrice]
    --   ,[ExtendedAmount]
    --   ,[UnitPriceDiscountPct]
    --   ,[DiscountAmount]
    --   ,[ProductStandardCost]
    --   ,[TotalProductCost]
      ,[SalesAmount]
    --   ,[TaxAmt]
    --   ,[Freight]
    --   ,[CarrierTrackingNumber]
    --   ,[CustomerPONumber]
    --   ,[OrderDate]
    --   ,[DueDate]
    --   ,[ShipDate]
  FROM [AdventureWorksDW2025].[dbo].[FactInternetSales]
  WHERE LEFT([OrderDateKey],4) >= 2024 -- filter for years 2024-2026 only (assumes we are in 2026 currently) --
  ORDER BY OrderDateKey ASC